version: 0.2

phases:
  install:
    commands:
      - echo "Installing phase skipped — static site"
  build:
    commands:
      - echo "Building static website"
      - mkdir -p dist
      - cp -r src/* dist/

artifacts:
  files:
    - '**/*'
  base-directory: dist

