version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # (Optional) Install npm/yarn packages if your frontend has dependencies

  build:
    commands:
      - echo "Building static website..."
      - mkdir -p dist
      - cp -r frontend/src/* dist/ || echo "No src folder found"
      - cp frontend/index.html dist/ || echo "No index.html found"
      - cp frontend/app.js dist/ || echo "No app.js found"
      - cp frontend/main.css dist/ || echo "No main.css found"
      - echo "Build completed successfully!"

  post_build:
    commands:
      - echo "Invoking listing Lambda..."
      - aws lambda invoke 
          --function-name listing-lambda 
          --region ap-south-1 
          --payload '{}' 
          output.json
      - echo "Lambda invoked. Check output.json for response."

artifacts:
  files:
    - '**/*'
  base-directory: dist

  secondary-artifacts:
    LambdaCode:
      base-directory: lambdas
      files:
        - index.py

