version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Add dependency commands if needed

  build:
    commands:
      - echo "Building static website..."
      - mkdir -p dist
      - cp -r frontend/src/* dist/ || echo "No src folder found"
      - cp frontend/index.html dist/ || echo "No index.html found"
      - cp frontend/app.js dist/ || echo "No app.js found"
      - cp frontend/main.css dist/ || echo "No main.css found"
      - echo "Build completed successfully!"

post_build:
  commands:
    - echo "Triggering Lambda..."
    - |
      aws lambda invoke \
        --function-name listing-lambda \
        --invocation-type Event \
        --cli-binary-format raw-in-base64-out \
        --payload '{"buildStatus":"SUCCESS"}' \
        response.json
    - echo "Lambda function invoked successfully."

artifacts:
  files:
    - '**/*'
  base-directory: dist


