version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building static website"
      - mkdir -p dist
      - cp -r * dist/
artifacts:
  base-directory: dist
  files:
    - '**/*'

