version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building static website"
      - mkdir -p dist
      - cp -r frontend/src/* dist/
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  base-directory: dist
  files:
    - '**/*'
